/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Nat;
export const PetType = IDL.Variant({ 'cat' : IDL.Null, 'dog' : IDL.Null });
export const VideoCategory = IDL.Variant({
  'healthTopic' : IDL.Text,
  'petType' : PetType,
  'breed' : IDL.Text,
});
export const VideoLink = IDL.Record({
  'id' : VideoId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : VideoCategory,
  'uploadedBy' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const YoutubeVideo = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
});
export const Breed = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'videos' : IDL.Vec(YoutubeVideo),
});
export const PetId = IDL.Nat;
export const Timestamp = IDL.Int;
export const VaccinationFrequency = IDL.Variant({
  'everyYear' : IDL.Null,
  'everyThreeYears' : IDL.Null,
});
export const Vaccination = IDL.Record({
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : Timestamp,
  'reminderFrequency' : VaccinationFrequency,
});
export const Gender = IDL.Variant({
  'other' : IDL.Text,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Pet = IDL.Record({
  'id' : PetId,
  'age' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Nat),
  'vaccinations' : IDL.Vec(Vaccination),
  'name' : IDL.Text,
  'petType' : PetType,
  'lastVaccinatedDate' : IDL.Opt(Timestamp),
  'gender' : Gender,
  'breed' : IDL.Opt(IDL.Text),
  'photo' : IDL.Opt(ExternalBlob),
});
export const PetCategory = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'videos' : IDL.Vec(YoutubeVideo),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Favorite = IDL.Record({ 'name' : IDL.Text, 'videoId' : VideoId });
export const UserProfile = IDL.Record({
  'favorites' : IDL.Vec(Favorite),
  'name' : IDL.Text,
  'pets' : IDL.Vec(Pet),
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminVideoLink' : IDL.Func([VideoLink], [VideoId], []),
  'addBreed' : IDL.Func([Breed], [], []),
  'addFavorite' : IDL.Func([VideoId, IDL.Text], [], []),
  'addPet' : IDL.Func([Pet], [PetId], []),
  'addPetCategory' : IDL.Func([PetCategory], [], []),
  'addVaccination' : IDL.Func(
      [PetId, IDL.Text, Timestamp, VaccinationFrequency],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBreeds' : IDL.Func([], [IDL.Vec(Breed)], ['query']),
  'getAllFavoriteVideos' : IDL.Func([], [IDL.Vec(Favorite)], ['query']),
  'getAllPetCategories' : IDL.Func([], [IDL.Vec(PetCategory)], ['query']),
  'getBreedsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Breed)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardInfo' : IDL.Func([], [UserProfile], ['query']),
  'getPet' : IDL.Func([PetId], [Pet], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVaccinationReminders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Vaccination)))],
      ['query'],
    ),
  'getVideosByCategory' : IDL.Func(
      [VideoCategory],
      [IDL.Vec(VideoLink)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markVaccinationCompleted' : IDL.Func([PetId, IDL.Text], [], []),
  'removeAdminVideoLink' : IDL.Func([VideoId], [], []),
  'removeBreed' : IDL.Func([IDL.Text], [], []),
  'removeFavorite' : IDL.Func([VideoId], [], []),
  'removePet' : IDL.Func([PetId], [], []),
  'removePetCategory' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitOnboardingPet' : IDL.Func([Pet], [PetId], []),
  'updateAdminVideoLink' : IDL.Func([VideoId, VideoLink], [], []),
  'updateBreed' : IDL.Func([IDL.Text, Breed], [], []),
  'updatePet' : IDL.Func([PetId, Pet], [], []),
  'updatePetCategory' : IDL.Func([IDL.Text, PetCategory], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Nat;
  const PetType = IDL.Variant({ 'cat' : IDL.Null, 'dog' : IDL.Null });
  const VideoCategory = IDL.Variant({
    'healthTopic' : IDL.Text,
    'petType' : PetType,
    'breed' : IDL.Text,
  });
  const VideoLink = IDL.Record({
    'id' : VideoId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : VideoCategory,
    'uploadedBy' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const YoutubeVideo = IDL.Record({ 'url' : IDL.Text, 'title' : IDL.Text });
  const Breed = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'videos' : IDL.Vec(YoutubeVideo),
  });
  const PetId = IDL.Nat;
  const Timestamp = IDL.Int;
  const VaccinationFrequency = IDL.Variant({
    'everyYear' : IDL.Null,
    'everyThreeYears' : IDL.Null,
  });
  const Vaccination = IDL.Record({
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : Timestamp,
    'reminderFrequency' : VaccinationFrequency,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Text,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Pet = IDL.Record({
    'id' : PetId,
    'age' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Nat),
    'vaccinations' : IDL.Vec(Vaccination),
    'name' : IDL.Text,
    'petType' : PetType,
    'lastVaccinatedDate' : IDL.Opt(Timestamp),
    'gender' : Gender,
    'breed' : IDL.Opt(IDL.Text),
    'photo' : IDL.Opt(ExternalBlob),
  });
  const PetCategory = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'videos' : IDL.Vec(YoutubeVideo),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Favorite = IDL.Record({ 'name' : IDL.Text, 'videoId' : VideoId });
  const UserProfile = IDL.Record({
    'favorites' : IDL.Vec(Favorite),
    'name' : IDL.Text,
    'pets' : IDL.Vec(Pet),
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminVideoLink' : IDL.Func([VideoLink], [VideoId], []),
    'addBreed' : IDL.Func([Breed], [], []),
    'addFavorite' : IDL.Func([VideoId, IDL.Text], [], []),
    'addPet' : IDL.Func([Pet], [PetId], []),
    'addPetCategory' : IDL.Func([PetCategory], [], []),
    'addVaccination' : IDL.Func(
        [PetId, IDL.Text, Timestamp, VaccinationFrequency],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBreeds' : IDL.Func([], [IDL.Vec(Breed)], ['query']),
    'getAllFavoriteVideos' : IDL.Func([], [IDL.Vec(Favorite)], ['query']),
    'getAllPetCategories' : IDL.Func([], [IDL.Vec(PetCategory)], ['query']),
    'getBreedsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Breed)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardInfo' : IDL.Func([], [UserProfile], ['query']),
    'getPet' : IDL.Func([PetId], [Pet], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVaccinationReminders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Vaccination)))],
        ['query'],
      ),
    'getVideosByCategory' : IDL.Func(
        [VideoCategory],
        [IDL.Vec(VideoLink)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markVaccinationCompleted' : IDL.Func([PetId, IDL.Text], [], []),
    'removeAdminVideoLink' : IDL.Func([VideoId], [], []),
    'removeBreed' : IDL.Func([IDL.Text], [], []),
    'removeFavorite' : IDL.Func([VideoId], [], []),
    'removePet' : IDL.Func([PetId], [], []),
    'removePetCategory' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitOnboardingPet' : IDL.Func([Pet], [PetId], []),
    'updateAdminVideoLink' : IDL.Func([VideoId, VideoLink], [], []),
    'updateBreed' : IDL.Func([IDL.Text, Breed], [], []),
    'updatePet' : IDL.Func([PetId, Pet], [], []),
    'updatePetCategory' : IDL.Func([IDL.Text, PetCategory], [], []),
  });
};

export const init = ({ IDL }) => { return []; };