/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Breed {
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'videos' : Array<YoutubeVideo>,
}
export type ExternalBlob = Uint8Array;
export interface Favorite { 'name' : string, 'videoId' : VideoId }
export type Gender = { 'other' : string } |
  { 'female' : null } |
  { 'male' : null };
export interface Pet {
  'id' : PetId,
  'age' : bigint,
  'weight' : [] | [bigint],
  'vaccinations' : Array<Vaccination>,
  'name' : string,
  'petType' : PetType,
  'lastVaccinatedDate' : [] | [Timestamp],
  'gender' : Gender,
  'breed' : [] | [string],
  'photo' : [] | [ExternalBlob],
}
export interface PetCategory {
  'name' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'videos' : Array<YoutubeVideo>,
}
export type PetId = bigint;
export type PetType = { 'cat' : null } |
  { 'dog' : null };
export type Timestamp = bigint;
export interface UserProfile {
  'favorites' : Array<Favorite>,
  'name' : string,
  'pets' : Array<Pet>,
  'profilePhoto' : [] | [ExternalBlob],
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vaccination {
  'name' : string,
  'completed' : boolean,
  'dueDate' : Timestamp,
  'reminderFrequency' : VaccinationFrequency,
}
export type VaccinationFrequency = { 'everyYear' : null } |
  { 'everyThreeYears' : null };
export type VideoCategory = { 'healthTopic' : string } |
  { 'petType' : PetType } |
  { 'breed' : string };
export type VideoId = bigint;
export interface VideoLink {
  'id' : VideoId,
  'url' : string,
  'title' : string,
  'description' : string,
  'category' : VideoCategory,
  'uploadedBy' : Principal,
}
export interface YoutubeVideo { 'url' : string, 'title' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminVideoLink' : ActorMethod<[VideoLink], VideoId>,
  'addBreed' : ActorMethod<[Breed], undefined>,
  'addFavorite' : ActorMethod<[VideoId, string], undefined>,
  'addPet' : ActorMethod<[Pet], PetId>,
  'addPetCategory' : ActorMethod<[PetCategory], undefined>,
  'addVaccination' : ActorMethod<
    [PetId, string, Timestamp, VaccinationFrequency],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBreeds' : ActorMethod<[], Array<Breed>>,
  'getAllFavoriteVideos' : ActorMethod<[], Array<Favorite>>,
  'getAllPetCategories' : ActorMethod<[], Array<PetCategory>>,
  'getBreedsByCategory' : ActorMethod<[string], Array<Breed>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardInfo' : ActorMethod<[], UserProfile>,
  'getPet' : ActorMethod<[PetId], Pet>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVaccinationReminders' : ActorMethod<
    [],
    Array<[string, Array<Vaccination>]>
  >,
  'getVideosByCategory' : ActorMethod<[VideoCategory], Array<VideoLink>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markVaccinationCompleted' : ActorMethod<[PetId, string], undefined>,
  'removeAdminVideoLink' : ActorMethod<[VideoId], undefined>,
  'removeBreed' : ActorMethod<[string], undefined>,
  'removeFavorite' : ActorMethod<[VideoId], undefined>,
  'removePet' : ActorMethod<[PetId], undefined>,
  'removePetCategory' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitOnboardingPet' : ActorMethod<[Pet], PetId>,
  'updateAdminVideoLink' : ActorMethod<[VideoId, VideoLink], undefined>,
  'updateBreed' : ActorMethod<[string, Breed], undefined>,
  'updatePet' : ActorMethod<[PetId, Pet], undefined>,
  'updatePetCategory' : ActorMethod<[string, PetCategory], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];