export interface BreedInfo {
  id: string;
  name: string;
  description: string;
  temperament: string;
  diet: string;
  careTips: string[];
  healthIssues: string[];
  videos: { title: string; url: string }[];
  imageUrl?: string;
}

export const breedsCatalog: Record<string, BreedInfo[]> = {
  cat: [
    {
      id: 'persian',
      name: 'Persian',
      description: 'Known for their long, luxurious coat and sweet personality, Persians are one of the most popular cat breeds.',
      temperament: 'Gentle, calm, and affectionate. They enjoy a quiet environment and are perfect lap cats.',
      diet: 'High-quality cat food with adequate protein. May need special food for hairball control.',
      careTips: ['Daily grooming required', 'Keep eyes clean', 'Indoor living recommended', 'Regular vet checkups'],
      healthIssues: ['Polycystic kidney disease', 'Respiratory issues', 'Eye problems', 'Dental disease'],
      videos: [
        { title: 'Persian Cat Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' },
        { title: 'Grooming Your Persian Cat', url: 'https://www.youtube.com/watch?v=Zs8siLxHQfg' },
      ],
      imageUrl: 'https://images.unsplash.com/photo-1589883661923-6476cb0ae9f2?w=800&h=500&fit=crop',
    },
    {
      id: 'siamese',
      name: 'Siamese',
      description: 'Vocal and social cats with striking blue eyes and color-point coats.',
      temperament: 'Highly intelligent, vocal, and social. They form strong bonds with their owners.',
      diet: 'High-protein diet with quality ingredients. Monitor weight carefully.',
      careTips: ['Provide mental stimulation', 'Interactive play daily', 'Social interaction essential', 'Minimal grooming needed'],
      healthIssues: ['Dental issues', 'Respiratory problems', 'Progressive retinal atrophy', 'Amyloidosis'],
      videos: [{ title: 'Siamese Cat Personality and Care', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800&h=500&fit=crop',
    },
    {
      id: 'maine-coon',
      name: 'Maine Coon',
      description: 'Large, gentle giants with tufted ears and bushy tails.',
      temperament: 'Friendly, playful, and adaptable. Great with families and other pets.',
      diet: 'High-calorie diet to support their large size. Quality protein sources essential.',
      careTips: ['Regular brushing', 'Provide climbing structures', 'Monitor for hip dysplasia', 'Plenty of space to roam'],
      healthIssues: ['Hip dysplasia', 'Hypertrophic cardiomyopathy', 'Spinal muscular atrophy'],
      videos: [{ title: 'Maine Coon Cat Complete Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=500&fit=crop',
    },
    {
      id: 'british-shorthair',
      name: 'British Shorthair',
      description: 'Sturdy, round-faced cats with dense coats and calm demeanor.',
      temperament: 'Easy-going, loyal, and independent. Good with children and other pets.',
      diet: 'Balanced diet with controlled portions to prevent obesity.',
      careTips: ['Weekly brushing', 'Monitor weight', 'Regular play sessions', 'Annual vet visits'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Obesity', 'Dental disease'],
      videos: [{ title: 'British Shorthair Cat Care', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=800&h=500&fit=crop',
    },
    {
      id: 'ragdoll',
      name: 'Ragdoll',
      description: 'Large, docile cats known for going limp when picked up.',
      temperament: 'Gentle, affectionate, and relaxed. Excellent family companions.',
      diet: 'High-quality protein-rich diet. Monitor portions to prevent obesity.',
      careTips: ['Regular grooming', 'Indoor only', 'Gentle handling', 'Interactive toys'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Polycystic kidney disease', 'Bladder stones'],
      videos: [{ title: 'Ragdoll Cat Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=800&h=500&fit=crop',
    },
    {
      id: 'bengal',
      name: 'Bengal',
      description: 'Wild-looking cats with leopard-like spots and energetic personalities.',
      temperament: 'Active, playful, and intelligent. Require lots of stimulation.',
      diet: 'High-protein diet with quality meat sources.',
      careTips: ['Extensive playtime', 'Climbing structures', 'Mental enrichment', 'Regular grooming'],
      healthIssues: ['Progressive retinal atrophy', 'Hypertrophic cardiomyopathy', 'Patellar luxation'],
      videos: [{ title: 'Bengal Cat Care and Training', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1618826411640-d6df44dd3f7a?w=800&h=500&fit=crop',
    },
    {
      id: 'sphynx',
      name: 'Sphynx',
      description: 'Hairless cats with wrinkled skin and extroverted personalities.',
      temperament: 'Energetic, affectionate, and attention-seeking. Very social.',
      diet: 'High-calorie diet due to higher metabolism.',
      careTips: ['Weekly bathing', 'Sun protection', 'Keep warm', 'Clean ears regularly'],
      healthIssues: ['Skin conditions', 'Hypertrophic cardiomyopathy', 'Respiratory issues'],
      videos: [{ title: 'Sphynx Cat Care Essentials', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=800&h=500&fit=crop',
    },
    {
      id: 'scottish-fold',
      name: 'Scottish Fold',
      description: 'Distinctive cats with folded ears and round faces.',
      temperament: 'Sweet-natured, adaptable, and moderately active.',
      diet: 'Balanced diet with quality ingredients.',
      careTips: ['Regular ear cleaning', 'Monitor joint health', 'Moderate exercise', 'Weekly grooming'],
      healthIssues: ['Osteochondrodysplasia', 'Ear infections', 'Arthritis'],
      videos: [{ title: 'Scottish Fold Cat Care', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?w=800&h=500&fit=crop',
    },
    {
      id: 'abyssinian',
      name: 'Abyssinian',
      description: 'Sleek, athletic cats with ticked coats and playful nature.',
      temperament: 'Active, curious, and intelligent. Love to climb and explore.',
      diet: 'High-protein diet to support active lifestyle.',
      careTips: ['Provide climbing opportunities', 'Interactive play', 'Mental stimulation', 'Minimal grooming'],
      healthIssues: ['Progressive retinal atrophy', 'Patellar luxation', 'Pyruvate kinase deficiency'],
      videos: [{ title: 'Abyssinian Cat Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=800&h=500&fit=crop',
    },
    {
      id: 'russian-blue',
      name: 'Russian Blue',
      description: 'Elegant cats with silvery-blue coats and green eyes.',
      temperament: 'Gentle, quiet, and somewhat shy. Loyal to family.',
      diet: 'Quality cat food with controlled portions.',
      careTips: ['Weekly brushing', 'Quiet environment', 'Routine important', 'Moderate play'],
      healthIssues: ['Generally healthy', 'Obesity if overfed', 'Bladder stones'],
      videos: [{ title: 'Russian Blue Cat Care', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=800&h=500&fit=crop',
    },
    {
      id: 'birman',
      name: 'Birman',
      description: 'Color-point cats with white paws and silky coats.',
      temperament: 'Gentle, social, and affectionate. Good with families.',
      diet: 'Balanced diet with quality protein.',
      careTips: ['Regular grooming', 'Social interaction', 'Indoor living', 'Moderate exercise'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Kidney disease', 'Corneal dermoid'],
      videos: [{ title: 'Birman Cat Care Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1573865526739-10c1d3a1f0cc?w=800&h=500&fit=crop',
    },
    {
      id: 'oriental',
      name: 'Oriental Shorthair',
      description: 'Sleek cats with large ears and diverse color patterns.',
      temperament: 'Vocal, social, and demanding of attention. Very intelligent.',
      diet: 'High-quality protein-rich diet.',
      careTips: ['Daily interaction', 'Mental stimulation', 'Minimal grooming', 'Warm environment'],
      healthIssues: ['Progressive retinal atrophy', 'Amyloidosis', 'Dental disease'],
      videos: [{ title: 'Oriental Shorthair Care', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?w=800&h=500&fit=crop',
    },
    {
      id: 'burmese',
      name: 'Burmese',
      description: 'Compact, muscular cats with silky coats and expressive eyes.',
      temperament: 'Affectionate, playful, and people-oriented. Very social.',
      diet: 'Quality diet with controlled portions.',
      careTips: ['Regular play', 'Social interaction', 'Weekly grooming', 'Indoor living'],
      healthIssues: ['Hypokalemia', 'Diabetes', 'Cranial deformities'],
      videos: [{ title: 'Burmese Cat Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?w=800&h=500&fit=crop',
    },
    {
      id: 'tonkinese',
      name: 'Tonkinese',
      description: 'Medium-sized cats with aqua eyes and mink-like coats.',
      temperament: 'Active, affectionate, and intelligent. Love human interaction.',
      diet: 'Balanced diet with quality ingredients.',
      careTips: ['Interactive play', 'Mental challenges', 'Social time', 'Minimal grooming'],
      healthIssues: ['Generally healthy', 'Gingivitis', 'Amyloidosis'],
      videos: [{ title: 'Tonkinese Cat Care', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?w=800&h=500&fit=crop',
    },
    {
      id: 'norwegian-forest',
      name: 'Norwegian Forest Cat',
      description: 'Large, sturdy cats with thick, water-resistant coats.',
      temperament: 'Friendly, independent, and adaptable. Good climbers.',
      diet: 'High-protein diet to support large frame.',
      careTips: ['Regular brushing', 'Climbing opportunities', 'Outdoor access if safe', 'Monitor weight'],
      healthIssues: ['Hip dysplasia', 'Hypertrophic cardiomyopathy', 'Glycogen storage disease'],
      videos: [{ title: 'Norwegian Forest Cat Care', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=500&fit=crop',
    },
    {
      id: 'devon-rex',
      name: 'Devon Rex',
      description: 'Pixie-like cats with curly coats and large ears.',
      temperament: 'Playful, mischievous, and affectionate. Very social.',
      diet: 'High-calorie diet due to higher metabolism.',
      careTips: ['Keep warm', 'Regular ear cleaning', 'Interactive play', 'Minimal grooming'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Patellar luxation', 'Hereditary myopathy'],
      videos: [{ title: 'Devon Rex Cat Care Guide', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?w=800&h=500&fit=crop',
    },
    {
      id: 'cornish-rex',
      name: 'Cornish Rex',
      description: 'Slender cats with wavy coats and elegant appearance.',
      temperament: 'Active, playful, and affectionate. Love to be involved.',
      diet: 'High-calorie diet to support metabolism.',
      careTips: ['Keep warm', 'Interactive play', 'Mental stimulation', 'Gentle grooming'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Patellar luxation', 'Umbilical hernia'],
      videos: [{ title: 'Cornish Rex Cat Care', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?w=800&h=500&fit=crop',
    },
    {
      id: 'exotic-shorthair',
      name: 'Exotic Shorthair',
      description: 'Persian-like cats with short, plush coats.',
      temperament: 'Gentle, calm, and affectionate. Easier to groom than Persians.',
      diet: 'Quality diet with controlled portions.',
      careTips: ['Weekly grooming', 'Clean eyes regularly', 'Indoor living', 'Moderate play'],
      healthIssues: ['Polycystic kidney disease', 'Respiratory issues', 'Eye problems'],
      videos: [{ title: 'Exotic Shorthair Care Guide', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1589883661923-6476cb0ae9f2?w=800&h=500&fit=crop',
    },
    {
      id: 'american-shorthair',
      name: 'American Shorthair',
      description: 'Sturdy, adaptable cats with round faces and diverse colors.',
      temperament: 'Easy-going, affectionate, and independent. Good hunters.',
      diet: 'Balanced diet with controlled portions.',
      careTips: ['Weekly grooming', 'Regular exercise', 'Monitor weight', 'Annual checkups'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Hip dysplasia', 'Obesity'],
      videos: [{ title: 'American Shorthair Cat Care', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=500&fit=crop',
    },
    {
      id: 'turkish-angora',
      name: 'Turkish Angora',
      description: 'Elegant cats with silky coats and graceful movements.',
      temperament: 'Intelligent, playful, and assertive. Very active.',
      diet: 'High-quality protein-rich diet.',
      careTips: ['Regular grooming', 'Mental stimulation', 'Interactive play', 'Climbing structures'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Ataxia', 'Deafness in white cats'],
      videos: [{ title: 'Turkish Angora Cat Care', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1573865526739-10c1d3a1f0cc?w=800&h=500&fit=crop',
    },
    {
      id: 'manx',
      name: 'Manx',
      description: 'Tailless or short-tailed cats with round appearance.',
      temperament: 'Playful, loyal, and dog-like. Good with families.',
      diet: 'Balanced diet with quality ingredients.',
      careTips: ['Monitor spine health', 'Regular exercise', 'Weekly grooming', 'Indoor living'],
      healthIssues: ['Manx syndrome', 'Spina bifida', 'Arthritis'],
      videos: [{ title: 'Manx Cat Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=500&fit=crop',
    },
    {
      id: 'somali',
      name: 'Somali',
      description: 'Long-haired version of Abyssinian with bushy tail.',
      temperament: 'Active, playful, and intelligent. Love to explore.',
      diet: 'High-protein diet for active lifestyle.',
      careTips: ['Regular grooming', 'Climbing opportunities', 'Interactive play', 'Mental challenges'],
      healthIssues: ['Progressive retinal atrophy', 'Pyruvate kinase deficiency', 'Renal amyloidosis'],
      videos: [{ title: 'Somali Cat Care', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=800&h=500&fit=crop',
    },
    {
      id: 'chartreux',
      name: 'Chartreux',
      description: 'Blue-gray cats with copper eyes and robust build.',
      temperament: 'Quiet, gentle, and observant. Loyal companions.',
      diet: 'Quality diet with controlled portions.',
      careTips: ['Weekly grooming', 'Moderate exercise', 'Quiet environment', 'Regular checkups'],
      healthIssues: ['Patellar luxation', 'Polycystic kidney disease', 'Generally healthy'],
      videos: [{ title: 'Chartreux Cat Care Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=800&h=500&fit=crop',
    },
    {
      id: 'balinese',
      name: 'Balinese',
      description: 'Long-haired Siamese with elegant appearance.',
      temperament: 'Vocal, social, and affectionate. Very intelligent.',
      diet: 'High-protein diet with quality ingredients.',
      careTips: ['Regular grooming', 'Social interaction', 'Mental stimulation', 'Interactive play'],
      healthIssues: ['Progressive retinal atrophy', 'Amyloidosis', 'Respiratory issues'],
      videos: [{ title: 'Balinese Cat Care', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800&h=500&fit=crop',
    },
    {
      id: 'havana-brown',
      name: 'Havana Brown',
      description: 'Chocolate-colored cats with green eyes.',
      temperament: 'Affectionate, playful, and social. Love human interaction.',
      diet: 'Quality diet with balanced nutrition.',
      careTips: ['Social interaction', 'Interactive play', 'Weekly grooming', 'Indoor living'],
      healthIssues: ['Upper respiratory infections', 'Calcium oxalate stones', 'Generally healthy'],
      videos: [{ title: 'Havana Brown Cat Care', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?w=800&h=500&fit=crop',
    },
    {
      id: 'ocicat',
      name: 'Ocicat',
      description: 'Spotted cats with wild appearance but domestic temperament.',
      temperament: 'Outgoing, social, and playful. Dog-like personality.',
      diet: 'High-quality protein-rich diet.',
      careTips: ['Interactive play', 'Social interaction', 'Mental stimulation', 'Minimal grooming'],
      healthIssues: ['Renal amyloidosis', 'Hypertrophic cardiomyopathy', 'Liver disease'],
      videos: [{ title: 'Ocicat Care Guide', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1618826411640-d6df44dd3f7a?w=800&h=500&fit=crop',
    },
    {
      id: 'japanese-bobtail',
      name: 'Japanese Bobtail',
      description: 'Cats with distinctive pom-pom tails and triangular faces.',
      temperament: 'Active, vocal, and intelligent. Very social.',
      diet: 'Balanced diet with quality ingredients.',
      careTips: ['Interactive play', 'Social interaction', 'Weekly grooming', 'Mental challenges'],
      healthIssues: ['Generally healthy', 'Occasional tail issues', 'Minimal genetic problems'],
      videos: [{ title: 'Japanese Bobtail Cat Care', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=500&fit=crop',
    },
    {
      id: 'singapura',
      name: 'Singapura',
      description: 'One of the smallest cat breeds with large eyes.',
      temperament: 'Playful, curious, and affectionate. Very active.',
      diet: 'High-quality diet appropriate for small size.',
      careTips: ['Keep warm', 'Interactive play', 'Social interaction', 'Minimal grooming'],
      healthIssues: ['Pyruvate kinase deficiency', 'Uterine inertia', 'Generally healthy'],
      videos: [{ title: 'Singapura Cat Care Guide', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?w=800&h=500&fit=crop',
    },
    {
      id: 'korat',
      name: 'Korat',
      description: 'Silver-blue cats with heart-shaped faces and green eyes.',
      temperament: 'Gentle, intelligent, and loyal. Form strong bonds.',
      diet: 'Quality diet with balanced nutrition.',
      careTips: ['Quiet environment', 'Social interaction', 'Weekly grooming', 'Indoor living'],
      healthIssues: ['Gangliosidosis', 'Generally healthy', 'Sensitive to anesthesia'],
      videos: [{ title: 'Korat Cat Care', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=800&h=500&fit=crop',
    },
    {
      id: 'selkirk-rex',
      name: 'Selkirk Rex',
      description: 'Cats with curly coats and round faces.',
      temperament: 'Patient, tolerant, and affectionate. Good with families.',
      diet: 'Balanced diet with quality ingredients.',
      careTips: ['Regular grooming', 'Monitor skin health', 'Moderate exercise', 'Social interaction'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Polycystic kidney disease', 'Hip dysplasia'],
      videos: [{ title: 'Selkirk Rex Cat Care Guide', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1583795128727-6ec3642408f8?w=800&h=500&fit=crop',
    },
    {
      id: 'ragamuffin',
      name: 'Ragamuffin',
      description: 'Large, docile cats with plush coats and sweet expressions.',
      temperament: 'Gentle, patient, and affectionate. Excellent family pets.',
      diet: 'Quality diet with controlled portions to prevent obesity.',
      careTips: ['Regular grooming', 'Indoor living', 'Moderate exercise', 'Social interaction'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Polycystic kidney disease', 'Obesity'],
      videos: [{ title: 'Ragamuffin Cat Care', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=800&h=500&fit=crop',
    },
  ],
  dog: [
    {
      id: 'golden-retriever',
      name: 'Golden Retriever',
      description: 'Friendly, intelligent, and devoted family dogs known for their golden coat.',
      temperament: 'Gentle, friendly, and eager to please. Excellent with children and families.',
      diet: 'High-quality dog food appropriate for their age and activity level. Monitor portions to prevent obesity.',
      careTips: ['Daily exercise required', 'Regular grooming', 'Mental stimulation', 'Socialization important'],
      healthIssues: ['Hip dysplasia', 'Elbow dysplasia', 'Heart disease', 'Cancer'],
      videos: [
        { title: 'Golden Retriever Training Guide', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' },
        { title: 'Golden Retriever Health Care', url: 'https://www.youtube.com/watch?v=TqMGMOJqBTQ' },
      ],
      imageUrl: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=800&h=500&fit=crop',
    },
    {
      id: 'german-shepherd',
      name: 'German Shepherd',
      description: 'Intelligent, versatile working dogs known for their loyalty and courage.',
      temperament: 'Confident, courageous, and smart. Excellent working and family dogs.',
      diet: 'High-protein diet with quality ingredients. Large breed formula recommended.',
      careTips: ['Extensive exercise needs', 'Mental challenges', 'Early socialization', 'Consistent training'],
      healthIssues: ['Hip and elbow dysplasia', 'Degenerative myelopathy', 'Bloat', 'Allergies'],
      videos: [{ title: 'German Shepherd Complete Care', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=500&fit=crop',
    },
    {
      id: 'labrador',
      name: 'Labrador Retriever',
      description: 'America\'s most popular dog breed, known for their friendly nature and versatility.',
      temperament: 'Outgoing, even-tempered, and gentle. Great family companions.',
      diet: 'Balanced diet with controlled portions. Prone to obesity if overfed.',
      careTips: ['High exercise needs', 'Swimming opportunities', 'Regular grooming', 'Training from young age'],
      healthIssues: ['Hip dysplasia', 'Elbow dysplasia', 'Eye conditions', 'Obesity'],
      videos: [{ title: 'Labrador Retriever Care Essentials', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=500&fit=crop',
    },
    {
      id: 'french-bulldog',
      name: 'French Bulldog',
      description: 'Small, muscular dogs with bat ears and playful personalities.',
      temperament: 'Affectionate, playful, and adaptable. Great apartment dogs.',
      diet: 'Quality diet with controlled portions. Avoid overfeeding.',
      careTips: ['Moderate exercise', 'Keep cool in heat', 'Clean facial folds', 'Monitor breathing'],
      healthIssues: ['Brachycephalic syndrome', 'Hip dysplasia', 'Allergies', 'Spinal disorders'],
      videos: [{ title: 'French Bulldog Care Guide', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=500&fit=crop',
    },
    {
      id: 'bulldog',
      name: 'Bulldog',
      description: 'Muscular, wrinkled dogs with distinctive pushed-in nose.',
      temperament: 'Calm, courageous, and friendly. Good with children.',
      diet: 'Quality diet appropriate for their size and activity level.',
      careTips: ['Moderate exercise', 'Clean wrinkles daily', 'Keep cool', 'Monitor breathing'],
      healthIssues: ['Brachycephalic syndrome', 'Hip dysplasia', 'Cherry eye', 'Skin infections'],
      videos: [{ title: 'Bulldog Care Essentials', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=500&fit=crop',
    },
    {
      id: 'beagle',
      name: 'Beagle',
      description: 'Small to medium hounds with excellent sense of smell.',
      temperament: 'Friendly, curious, and merry. Great family dogs.',
      diet: 'Quality diet with controlled portions. Prone to obesity.',
      careTips: ['Daily exercise', 'Mental stimulation', 'Secure fencing', 'Regular ear cleaning'],
      healthIssues: ['Hip dysplasia', 'Epilepsy', 'Hypothyroidism', 'Ear infections'],
      videos: [{ title: 'Beagle Training and Care', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800&h=500&fit=crop',
    },
    {
      id: 'poodle',
      name: 'Poodle',
      description: 'Intelligent, elegant dogs available in three sizes.',
      temperament: 'Smart, active, and proud. Excellent trainability.',
      diet: 'High-quality diet appropriate for size and activity level.',
      careTips: ['Regular grooming', 'Mental stimulation', 'Daily exercise', 'Professional grooming'],
      healthIssues: ['Hip dysplasia', 'Progressive retinal atrophy', 'Epilepsy', 'Addison\'s disease'],
      videos: [{ title: 'Poodle Care and Grooming', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1616080484084-8c19e7e0e9e0?w=800&h=500&fit=crop',
    },
    {
      id: 'rottweiler',
      name: 'Rottweiler',
      description: 'Large, powerful dogs with strong protective instincts.',
      temperament: 'Confident, loyal, and courageous. Need proper training.',
      diet: 'Large breed formula with quality protein.',
      careTips: ['Early socialization', 'Consistent training', 'Daily exercise', 'Mental challenges'],
      healthIssues: ['Hip dysplasia', 'Elbow dysplasia', 'Osteosarcoma', 'Bloat'],
      videos: [{ title: 'Rottweiler Training Guide', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&h=500&fit=crop',
    },
    {
      id: 'yorkshire-terrier',
      name: 'Yorkshire Terrier',
      description: 'Small terriers with long, silky coats and big personalities.',
      temperament: 'Affectionate, sprightly, and tomboyish. Confident despite size.',
      diet: 'Small breed formula with quality ingredients.',
      careTips: ['Daily grooming', 'Dental care', 'Moderate exercise', 'Socialization'],
      healthIssues: ['Patellar luxation', 'Portosystemic shunt', 'Tracheal collapse', 'Dental disease'],
      videos: [{ title: 'Yorkshire Terrier Care', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=500&fit=crop',
    },
    {
      id: 'boxer',
      name: 'Boxer',
      description: 'Medium to large dogs with square muzzles and boundless energy.',
      temperament: 'Playful, energetic, and loyal. Great with families.',
      diet: 'High-quality diet for active breeds.',
      careTips: ['High exercise needs', 'Mental stimulation', 'Early training', 'Monitor in heat'],
      healthIssues: ['Cardiomyopathy', 'Hip dysplasia', 'Cancer', 'Bloat'],
      videos: [{ title: 'Boxer Dog Care Guide', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&h=500&fit=crop',
    },
    {
      id: 'dachshund',
      name: 'Dachshund',
      description: 'Long-bodied, short-legged dogs with lively personalities.',
      temperament: 'Clever, lively, and courageous. Can be stubborn.',
      diet: 'Quality diet with controlled portions to prevent obesity.',
      careTips: ['Prevent jumping', 'Support spine', 'Moderate exercise', 'Dental care'],
      healthIssues: ['Intervertebral disc disease', 'Obesity', 'Dental disease', 'Patellar luxation'],
      videos: [{ title: 'Dachshund Care Essentials', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=800&h=500&fit=crop',
    },
    {
      id: 'siberian-husky',
      name: 'Siberian Husky',
      description: 'Medium-sized working dogs with thick coats and striking eyes.',
      temperament: 'Outgoing, mischievous, and loyal. High energy.',
      diet: 'High-quality diet for active breeds.',
      careTips: ['Extensive exercise', 'Secure fencing', 'Regular grooming', 'Mental stimulation'],
      healthIssues: ['Hip dysplasia', 'Eye conditions', 'Hypothyroidism', 'Zinc deficiency'],
      videos: [{ title: 'Siberian Husky Care Guide', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=800&h=500&fit=crop',
    },
    {
      id: 'great-dane',
      name: 'Great Dane',
      description: 'Giant dogs known as gentle giants with noble appearance.',
      temperament: 'Friendly, patient, and dependable. Good with children.',
      diet: 'Large/giant breed formula. Multiple small meals.',
      careTips: ['Moderate exercise', 'Prevent bloat', 'Joint support', 'Space requirements'],
      healthIssues: ['Bloat', 'Hip dysplasia', 'Cardiomyopathy', 'Bone cancer'],
      videos: [{ title: 'Great Dane Care and Training', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&h=500&fit=crop',
    },
    {
      id: 'doberman',
      name: 'Doberman Pinscher',
      description: 'Sleek, powerful dogs with alert and loyal nature.',
      temperament: 'Loyal, fearless, and alert. Excellent guard dogs.',
      diet: 'High-quality diet for large active breeds.',
      careTips: ['Daily exercise', 'Mental challenges', 'Early socialization', 'Consistent training'],
      healthIssues: ['Dilated cardiomyopathy', 'Hip dysplasia', 'Von Willebrand\'s disease', 'Wobbler syndrome'],
      videos: [{ title: 'Doberman Care Guide', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&h=500&fit=crop',
    },
    {
      id: 'shih-tzu',
      name: 'Shih Tzu',
      description: 'Small, sturdy dogs with long, flowing coats.',
      temperament: 'Affectionate, playful, and outgoing. Great companions.',
      diet: 'Small breed formula with quality ingredients.',
      careTips: ['Daily grooming', 'Clean face daily', 'Moderate exercise', 'Dental care'],
      healthIssues: ['Brachycephalic syndrome', 'Hip dysplasia', 'Eye problems', 'Dental disease'],
      videos: [{ title: 'Shih Tzu Care and Grooming', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1612536980005-c6c5c3e8c0e0?w=800&h=500&fit=crop',
    },
    {
      id: 'boston-terrier',
      name: 'Boston Terrier',
      description: 'Small, compact dogs with tuxedo-like markings.',
      temperament: 'Friendly, bright, and amusing. Great city dogs.',
      diet: 'Quality diet appropriate for small breeds.',
      careTips: ['Moderate exercise', 'Keep cool', 'Clean facial folds', 'Monitor breathing'],
      healthIssues: ['Brachycephalic syndrome', 'Eye problems', 'Patellar luxation', 'Deafness'],
      videos: [{ title: 'Boston Terrier Care Guide', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=500&fit=crop',
    },
    {
      id: 'pomeranian',
      name: 'Pomeranian',
      description: 'Tiny dogs with fluffy coats and fox-like faces.',
      temperament: 'Inquisitive, bold, and lively. Big personality in small package.',
      diet: 'Small breed formula with quality ingredients.',
      careTips: ['Regular grooming', 'Dental care', 'Socialization', 'Moderate exercise'],
      healthIssues: ['Patellar luxation', 'Tracheal collapse', 'Dental disease', 'Alopecia X'],
      videos: [{ title: 'Pomeranian Care Essentials', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=800&h=500&fit=crop',
    },
    {
      id: 'australian-shepherd',
      name: 'Australian Shepherd',
      description: 'Medium-sized herding dogs with striking coat patterns.',
      temperament: 'Smart, work-oriented, and exuberant. Need jobs to do.',
      diet: 'High-quality diet for active breeds.',
      careTips: ['Extensive exercise', 'Mental challenges', 'Regular grooming', 'Early training'],
      healthIssues: ['Hip dysplasia', 'Epilepsy', 'Eye problems', 'MDR1 gene mutation'],
      videos: [{ title: 'Australian Shepherd Training', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=500&fit=crop',
    },
    {
      id: 'cavalier',
      name: 'Cavalier King Charles Spaniel',
      description: 'Small spaniels with gentle expressions and affectionate nature.',
      temperament: 'Affectionate, gentle, and graceful. Excellent companions.',
      diet: 'Quality diet with controlled portions.',
      careTips: ['Moderate exercise', 'Regular grooming', 'Heart monitoring', 'Dental care'],
      healthIssues: ['Mitral valve disease', 'Syringomyelia', 'Hip dysplasia', 'Eye problems'],
      videos: [{ title: 'Cavalier King Charles Care', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=500&fit=crop',
    },
    {
      id: 'miniature-schnauzer',
      name: 'Miniature Schnauzer',
      description: 'Small, sturdy dogs with distinctive beards and eyebrows.',
      temperament: 'Friendly, smart, and obedient. Good watchdogs.',
      diet: 'Quality diet appropriate for small breeds.',
      careTips: ['Regular grooming', 'Daily exercise', 'Mental stimulation', 'Dental care'],
      healthIssues: ['Pancreatitis', 'Diabetes', 'Bladder stones', 'Eye problems'],
      videos: [{ title: 'Miniature Schnauzer Care Guide', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=500&fit=crop',
    },
    {
      id: 'cocker-spaniel',
      name: 'Cocker Spaniel',
      description: 'Medium-sized sporting dogs with long, silky ears.',
      temperament: 'Gentle, smart, and happy. Great family dogs.',
      diet: 'Quality diet with controlled portions.',
      careTips: ['Regular grooming', 'Ear cleaning', 'Daily exercise', 'Eye care'],
      healthIssues: ['Ear infections', 'Eye problems', 'Hip dysplasia', 'Autoimmune diseases'],
      videos: [{ title: 'Cocker Spaniel Care', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=500&fit=crop',
    },
    {
      id: 'border-collie',
      name: 'Border Collie',
      description: 'Highly intelligent herding dogs with intense work drive.',
      temperament: 'Smart, energetic, and acutely aware. Need mental stimulation.',
      diet: 'High-quality diet for active breeds.',
      careTips: ['Extensive exercise', 'Mental challenges', 'Training essential', 'Regular grooming'],
      healthIssues: ['Hip dysplasia', 'Epilepsy', 'Collie eye anomaly', 'Deafness'],
      videos: [{ title: 'Border Collie Training Guide', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=500&fit=crop',
    },
    {
      id: 'chihuahua',
      name: 'Chihuahua',
      description: 'Tiny dogs with big personalities and alert expressions.',
      temperament: 'Charming, graceful, and sassy. Very loyal.',
      diet: 'Small breed formula. Small frequent meals.',
      careTips: ['Keep warm', 'Dental care', 'Socialization', 'Gentle handling'],
      healthIssues: ['Patellar luxation', 'Heart problems', 'Hypoglycemia', 'Dental disease'],
      videos: [{ title: 'Chihuahua Care Essentials', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=500&fit=crop',
    },
    {
      id: 'pembroke-corgi',
      name: 'Pembroke Welsh Corgi',
      description: 'Short-legged herding dogs with fox-like appearance.',
      temperament: 'Affectionate, smart, and alert. Good with families.',
      diet: 'Quality diet with controlled portions to prevent obesity.',
      careTips: ['Prevent jumping', 'Daily exercise', 'Regular grooming', 'Weight management'],
      healthIssues: ['Hip dysplasia', 'Intervertebral disc disease', 'Eye problems', 'Obesity'],
      videos: [{ title: 'Pembroke Welsh Corgi Care', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?w=800&h=500&fit=crop',
    },
    {
      id: 'shetland-sheepdog',
      name: 'Shetland Sheepdog',
      description: 'Small to medium herding dogs resembling miniature Collies.',
      temperament: 'Playful, energetic, and obedient. Very trainable.',
      diet: 'Quality diet appropriate for their size and activity.',
      careTips: ['Regular grooming', 'Daily exercise', 'Mental stimulation', 'Early socialization'],
      healthIssues: ['Hip dysplasia', 'Collie eye anomaly', 'Von Willebrand\'s disease', 'Hypothyroidism'],
      videos: [{ title: 'Shetland Sheepdog Care Guide', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=500&fit=crop',
    },
    {
      id: 'bernese-mountain-dog',
      name: 'Bernese Mountain Dog',
      description: 'Large, sturdy dogs with distinctive tri-color coats.',
      temperament: 'Good-natured, calm, and strong. Great family dogs.',
      diet: 'Large breed formula with quality ingredients.',
      careTips: ['Moderate exercise', 'Regular grooming', 'Keep cool', 'Joint support'],
      healthIssues: ['Hip dysplasia', 'Elbow dysplasia', 'Cancer', 'Bloat'],
      videos: [{ title: 'Bernese Mountain Dog Care', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&h=500&fit=crop',
    },
    {
      id: 'mastiff',
      name: 'Mastiff',
      description: 'Giant dogs with massive build and gentle temperament.',
      temperament: 'Good-natured, dignified, and courageous. Gentle giants.',
      diet: 'Giant breed formula. Multiple small meals.',
      careTips: ['Moderate exercise', 'Prevent bloat', 'Clean facial folds', 'Space requirements'],
      healthIssues: ['Hip dysplasia', 'Bloat', 'Heart problems', 'Eye problems'],
      videos: [{ title: 'Mastiff Care Guide', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&h=500&fit=crop',
    },
    {
      id: 'weimaraner',
      name: 'Weimaraner',
      description: 'Large sporting dogs with distinctive gray coats.',
      temperament: 'Friendly, fearless, and alert. High energy.',
      diet: 'High-quality diet for active large breeds.',
      careTips: ['Extensive exercise', 'Mental stimulation', 'Early training', 'Prevent bloat'],
      healthIssues: ['Hip dysplasia', 'Bloat', 'Von Willebrand\'s disease', 'Hypothyroidism'],
      videos: [{ title: 'Weimaraner Training and Care', url: 'https://www.youtube.com/watch?v=wZv62ShoStY' }],
      imageUrl: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=500&fit=crop',
    },
    {
      id: 'newfoundland',
      name: 'Newfoundland',
      description: 'Giant dogs known for their swimming ability and gentle nature.',
      temperament: 'Sweet-tempered, gentle, and trainable. Excellent with children.',
      diet: 'Giant breed formula with quality ingredients.',
      careTips: ['Moderate exercise', 'Swimming opportunities', 'Regular grooming', 'Keep cool'],
      healthIssues: ['Hip dysplasia', 'Elbow dysplasia', 'Heart disease', 'Cystinuria'],
      videos: [{ title: 'Newfoundland Dog Care', url: 'https://www.youtube.com/watch?v=dCqrTFJAHKE' }],
      imageUrl: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&h=500&fit=crop',
    },
    {
      id: 'rhodesian-ridgeback',
      name: 'Rhodesian Ridgeback',
      description: 'Large hounds with distinctive ridge of hair along their backs.',
      temperament: 'Dignified, intelligent, and even-tempered. Independent.',
      diet: 'High-quality diet for large active breeds.',
      careTips: ['Daily exercise', 'Early socialization', 'Consistent training', 'Minimal grooming'],
      healthIssues: ['Hip dysplasia', 'Elbow dysplasia', 'Dermoid sinus', 'Hypothyroidism'],
      videos: [{ title: 'Rhodesian Ridgeback Care Guide', url: 'https://www.youtube.com/watch?v=EPYy_h3NvWs' }],
      imageUrl: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&h=500&fit=crop',
    },
  ],
  bird: [
    {
      id: 'african-grey',
      name: 'African Grey Parrot',
      description: 'Highly intelligent parrots known for their exceptional talking ability.',
      temperament: 'Intelligent, sensitive, and social. Require significant mental stimulation.',
      diet: 'Pellets, fresh fruits, vegetables, and nuts. Avoid avocado and chocolate.',
      careTips: ['Daily interaction required', 'Large cage needed', 'Mental enrichment', 'Regular vet checkups'],
      healthIssues: ['Feather plucking', 'Calcium deficiency', 'Respiratory infections', 'Psittacine beak disease'],
      videos: [{ title: 'African Grey Parrot Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'cockatiel',
      name: 'Cockatiel',
      description: 'Small, friendly parrots with distinctive crests and cheerful personalities.',
      temperament: 'Friendly, social, and affectionate. Great for first-time bird owners.',
      diet: 'Pellets, seeds, fresh vegetables, and occasional fruits.',
      careTips: ['Daily out-of-cage time', 'Social interaction', 'Toys for enrichment', 'Regular nail trimming'],
      healthIssues: ['Fatty liver disease', 'Egg binding in females', 'Respiratory infections'],
      videos: [{ title: 'Cockatiel Care for Beginners', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=800&h=500&fit=crop',
    },
    {
      id: 'budgerigar',
      name: 'Budgerigar (Budgie)',
      description: 'Small, colorful parakeets that are popular pet birds.',
      temperament: 'Playful, social, and intelligent. Can learn to talk.',
      diet: 'Seeds, pellets, fresh vegetables, and occasional fruits.',
      careTips: ['Daily interaction', 'Toys for enrichment', 'Clean cage regularly', 'Flight time'],
      healthIssues: ['Tumors', 'Mites', 'Respiratory infections', 'Fatty liver disease'],
      videos: [{ title: 'Budgie Care Complete Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'macaw',
      name: 'Macaw',
      description: 'Large, colorful parrots with powerful beaks and long tails.',
      temperament: 'Intelligent, social, and playful. Need experienced owners.',
      diet: 'Pellets, nuts, fruits, and vegetables. High-fat diet.',
      careTips: ['Very large cage', 'Daily interaction', 'Mental stimulation', 'Strong toys'],
      healthIssues: ['Feather plucking', 'Proventricular dilatation disease', 'Psittacosis', 'Beak malformations'],
      videos: [{ title: 'Macaw Care and Training', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'amazon-parrot',
      name: 'Amazon Parrot',
      description: 'Medium to large parrots known for their talking ability and vibrant colors.',
      temperament: 'Outgoing, playful, and intelligent. Can be loud.',
      diet: 'Pellets, fruits, vegetables, and occasional nuts.',
      careTips: ['Large cage', 'Daily interaction', 'Mental enrichment', 'Training essential'],
      healthIssues: ['Obesity', 'Vitamin A deficiency', 'Psittacosis', 'Feather plucking'],
      videos: [{ title: 'Amazon Parrot Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'conure',
      name: 'Conure',
      description: 'Small to medium parrots with playful personalities and bright colors.',
      temperament: 'Energetic, affectionate, and social. Can be noisy.',
      diet: 'Pellets, fruits, vegetables, and occasional seeds.',
      careTips: ['Daily interaction', 'Toys for enrichment', 'Social time', 'Regular bathing'],
      healthIssues: ['Proventricular dilatation disease', 'Feather plucking', 'Respiratory infections'],
      videos: [{ title: 'Conure Care and Training', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'lovebird',
      name: 'Lovebird',
      description: 'Small parrots known for their affectionate pair bonding.',
      temperament: 'Energetic, curious, and social. Best in pairs.',
      diet: 'Pellets, seeds, fresh vegetables, and fruits.',
      careTips: ['Social interaction', 'Toys for enrichment', 'Regular cage cleaning', 'Flight time'],
      healthIssues: ['Egg binding', 'Feather plucking', 'Respiratory infections', 'Obesity'],
      videos: [{ title: 'Lovebird Care Essentials', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'cockatoo',
      name: 'Cockatoo',
      description: 'Large parrots with impressive crests and affectionate nature.',
      temperament: 'Affectionate, demanding, and intelligent. Need lots of attention.',
      diet: 'Pellets, nuts, fruits, and vegetables.',
      careTips: ['Very large cage', 'Extensive daily interaction', 'Mental stimulation', 'Dust management'],
      healthIssues: ['Feather plucking', 'Psittacine beak disease', 'Fatty liver disease', 'Self-mutilation'],
      videos: [{ title: 'Cockatoo Care Guide', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'canary',
      name: 'Canary',
      description: 'Small songbirds known for their beautiful singing.',
      temperament: 'Independent, melodious, and peaceful. Males sing more.',
      diet: 'Canary seed mix, fresh vegetables, and occasional fruits.',
      careTips: ['Clean cage regularly', 'Provide perches', 'Quiet environment', 'Regular bathing'],
      healthIssues: ['Mites', 'Respiratory infections', 'Egg binding in females', 'Overgrown nails'],
      videos: [{ title: 'Canary Care and Training', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'finch',
      name: 'Finch',
      description: 'Small, active birds that do well in groups.',
      temperament: 'Social, active, and peaceful. Best in pairs or groups.',
      diet: 'Finch seed mix, fresh vegetables, and occasional fruits.',
      careTips: ['Keep in pairs', 'Flight cage', 'Clean regularly', 'Minimal handling'],
      healthIssues: ['Mites', 'Respiratory infections', 'Egg binding', 'Overgrown nails'],
      videos: [{ title: 'Finch Care Guide', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'parrotlet',
      name: 'Parrotlet',
      description: 'Tiny parrots with big personalities.',
      temperament: 'Bold, feisty, and affectionate. Fearless despite size.',
      diet: 'Pellets, seeds, fresh vegetables, and fruits.',
      careTips: ['Daily interaction', 'Toys for enrichment', 'Social time', 'Regular nail trimming'],
      healthIssues: ['Obesity', 'Feather plucking', 'Respiratory infections', 'Egg binding'],
      videos: [{ title: 'Parrotlet Care Essentials', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'quaker-parrot',
      name: 'Quaker Parrot',
      description: 'Small to medium parrots known for their talking ability.',
      temperament: 'Social, intelligent, and bold. Can be territorial.',
      diet: 'Pellets, fruits, vegetables, and occasional seeds.',
      careTips: ['Daily interaction', 'Mental stimulation', 'Training essential', 'Toys for enrichment'],
      healthIssues: ['Fatty liver disease', 'Feather plucking', 'Psittacosis', 'Obesity'],
      videos: [{ title: 'Quaker Parrot Care Guide', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'eclectus',
      name: 'Eclectus Parrot',
      description: 'Large parrots with striking sexual dimorphism in coloration.',
      temperament: 'Gentle, intelligent, and calm. Good for experienced owners.',
      diet: 'Fresh fruits, vegetables, and limited pellets. High fiber diet.',
      careTips: ['Large cage', 'Daily interaction', 'Fresh food daily', 'Mental enrichment'],
      healthIssues: ['Toe tapping', 'Wing flipping', 'Feather plucking', 'Vitamin A toxicity'],
      videos: [{ title: 'Eclectus Parrot Care', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'caique',
      name: 'Caique',
      description: 'Small to medium parrots known for their playful antics.',
      temperament: 'Energetic, playful, and comical. Very active.',
      diet: 'Pellets, fruits, vegetables, and occasional nuts.',
      careTips: ['Daily interaction', 'Lots of toys', 'Mental stimulation', 'Supervised playtime'],
      healthIssues: ['Polyomavirus', 'Feather plucking', 'Obesity', 'Respiratory infections'],
      videos: [{ title: 'Caique Care and Training', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'senegal-parrot',
      name: 'Senegal Parrot',
      description: 'Small to medium parrots with quiet, gentle nature.',
      temperament: 'Quiet, gentle, and affectionate. Good apartment birds.',
      diet: 'Pellets, fruits, vegetables, and occasional seeds.',
      careTips: ['Daily interaction', 'Mental enrichment', 'Moderate toys', 'Regular bathing'],
      healthIssues: ['Aspergillosis', 'Feather plucking', 'Obesity', 'Calcium deficiency'],
      videos: [{ title: 'Senegal Parrot Care Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'pionus',
      name: 'Pionus Parrot',
      description: 'Medium-sized parrots known for their quiet nature.',
      temperament: 'Gentle, quiet, and even-tempered. Good for apartments.',
      diet: 'Pellets, fruits, vegetables, and occasional nuts.',
      careTips: ['Daily interaction', 'Mental enrichment', 'Regular bathing', 'Moderate exercise'],
      healthIssues: ['Aspergillosis', 'Vitamin A deficiency', 'Obesity', 'Feather plucking'],
      videos: [{ title: 'Pionus Parrot Care', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'lorikeet',
      name: 'Lorikeet',
      description: 'Colorful parrots with specialized brush-tipped tongues.',
      temperament: 'Energetic, playful, and social. Very active.',
      diet: 'Nectar, pollen, fruits, and vegetables. Specialized diet.',
      careTips: ['Frequent cage cleaning', 'Daily interaction', 'Fresh nectar daily', 'Bathing opportunities'],
      healthIssues: ['Hemochromatosis', 'Bacterial infections', 'Feather plucking', 'Obesity'],
      videos: [{ title: 'Lorikeet Care Essentials', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'parakeet',
      name: 'Parakeet',
      description: 'Small to medium parrots with long tails and varied colors.',
      temperament: 'Social, playful, and intelligent. Good for beginners.',
      diet: 'Seeds, pellets, fresh vegetables, and fruits.',
      careTips: ['Daily interaction', 'Toys for enrichment', 'Flight time', 'Social companionship'],
      healthIssues: ['Tumors', 'Mites', 'Respiratory infections', 'Obesity'],
      videos: [{ title: 'Parakeet Care Guide', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'rosella',
      name: 'Rosella',
      description: 'Colorful Australian parrots with beautiful plumage.',
      temperament: 'Independent, active, and melodious. Less cuddly.',
      diet: 'Seeds, pellets, fruits, and vegetables.',
      careTips: ['Large flight cage', 'Minimal handling', 'Fresh food daily', 'Quiet environment'],
      healthIssues: ['Psittacosis', 'Feather plucking', 'Respiratory infections', 'Obesity'],
      videos: [{ title: 'Rosella Care and Housing', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'ring-necked-parakeet',
      name: 'Ring-Necked Parakeet',
      description: 'Medium-sized parakeets with distinctive neck rings.',
      temperament: 'Intelligent, independent, and vocal. Can learn tricks.',
      diet: 'Pellets, seeds, fruits, and vegetables.',
      careTips: ['Large cage', 'Daily interaction', 'Mental stimulation', 'Training essential'],
      healthIssues: ['Psittacosis', 'Feather plucking', 'Obesity', 'Respiratory infections'],
      videos: [{ title: 'Ring-Necked Parakeet Care', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'meyer-parrot',
      name: 'Meyer\'s Parrot',
      description: 'Small African parrots with quiet, gentle nature.',
      temperament: 'Quiet, gentle, and affectionate. Good for apartments.',
      diet: 'Pellets, fruits, vegetables, and occasional seeds.',
      careTips: ['Daily interaction', 'Mental enrichment', 'Moderate toys', 'Regular bathing'],
      healthIssues: ['Aspergillosis', 'Feather plucking', 'Obesity', 'Calcium deficiency'],
      videos: [{ title: 'Meyer\'s Parrot Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'jardine-parrot',
      name: 'Jardine\'s Parrot',
      description: 'Medium-sized African parrots with calm temperament.',
      temperament: 'Calm, gentle, and intelligent. Good for families.',
      diet: 'Pellets, fruits, vegetables, and occasional nuts.',
      careTips: ['Daily interaction', 'Mental enrichment', 'Regular bathing', 'Moderate exercise'],
      healthIssues: ['Aspergillosis', 'Feather plucking', 'Obesity', 'Vitamin A deficiency'],
      videos: [{ title: 'Jardine\'s Parrot Care', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'red-bellied-parrot',
      name: 'Red-Bellied Parrot',
      description: 'Small African parrots with quiet, gentle nature.',
      temperament: 'Quiet, gentle, and affectionate. Good apartment birds.',
      diet: 'Pellets, fruits, vegetables, and occasional seeds.',
      careTips: ['Daily interaction', 'Mental enrichment', 'Moderate toys', 'Regular bathing'],
      healthIssues: ['Aspergillosis', 'Feather plucking', 'Obesity', 'Calcium deficiency'],
      videos: [{ title: 'Red-Bellied Parrot Care Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'lineolated-parakeet',
      name: 'Lineolated Parakeet',
      description: 'Small, quiet parakeets with gentle personalities.',
      temperament: 'Gentle, quiet, and affectionate. Good for apartments.',
      diet: 'Pellets, seeds, fresh vegetables, and fruits.',
      careTips: ['Daily interaction', 'Toys for enrichment', 'Social time', 'Regular bathing'],
      healthIssues: ['Obesity', 'Feather plucking', 'Respiratory infections', 'Egg binding'],
      videos: [{ title: 'Lineolated Parakeet Care', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'bourke-parakeet',
      name: 'Bourke\'s Parakeet',
      description: 'Small, gentle parakeets with soft colors.',
      temperament: 'Gentle, quiet, and peaceful. Good for beginners.',
      diet: 'Seeds, pellets, fresh vegetables, and fruits.',
      careTips: ['Daily interaction', 'Flight time', 'Quiet environment', 'Minimal handling'],
      healthIssues: ['Mites', 'Respiratory infections', 'Egg binding', 'Obesity'],
      videos: [{ title: 'Bourke\'s Parakeet Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'kakariki',
      name: 'Kakariki',
      description: 'Small New Zealand parrots with energetic nature.',
      temperament: 'Energetic, playful, and curious. Very active.',
      diet: 'Pellets, seeds, fruits, and vegetables.',
      careTips: ['Large flight cage', 'Daily interaction', 'Lots of toys', 'Mental stimulation'],
      healthIssues: ['Obesity', 'Feather plucking', 'Respiratory infections', 'Egg binding'],
      videos: [{ title: 'Kakariki Care and Training', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'princess-parrot',
      name: 'Princess Parrot',
      description: 'Elegant Australian parrots with long tails.',
      temperament: 'Gentle, quiet, and independent. Less cuddly.',
      diet: 'Seeds, pellets, fruits, and vegetables.',
      careTips: ['Large flight cage', 'Minimal handling', 'Fresh food daily', 'Quiet environment'],
      healthIssues: ['Psittacosis', 'Feather plucking', 'Respiratory infections', 'Obesity'],
      videos: [{ title: 'Princess Parrot Care', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'crimson-rosella',
      name: 'Crimson Rosella',
      description: 'Beautiful red Australian parrots with blue wings.',
      temperament: 'Independent, active, and melodious. Less cuddly.',
      diet: 'Seeds, pellets, fruits, and vegetables.',
      careTips: ['Large flight cage', 'Minimal handling', 'Fresh food daily', 'Quiet environment'],
      healthIssues: ['Psittacosis', 'Feather plucking', 'Respiratory infections', 'Obesity'],
      videos: [{ title: 'Crimson Rosella Care Guide', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'turquoisine-parrot',
      name: 'Turquoisine Parrot',
      description: 'Small Australian parrots with beautiful turquoise coloring.',
      temperament: 'Gentle, quiet, and peaceful. Good for aviaries.',
      diet: 'Seeds, pellets, fruits, and vegetables.',
      careTips: ['Flight cage', 'Minimal handling', 'Fresh food daily', 'Quiet environment'],
      healthIssues: ['Psittacosis', 'Feather plucking', 'Respiratory infections', 'Obesity'],
      videos: [{ title: 'Turquoisine Parrot Care', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
  ],
};
