export interface BreedInfo {
  id: string;
  name: string;
  description: string;
  temperament: string;
  diet: string;
  careTips: string[];
  healthIssues: string[];
  videos: { title: string; url: string }[];
  imageUrl?: string;
}

export const breedsCatalog: Record<string, BreedInfo[]> = {
  cat: [
    {
      id: 'persian',
      name: 'Persian',
      description: 'Known for their long, luxurious coat and sweet personality, Persians are one of the most popular cat breeds.',
      temperament: 'Gentle, calm, and affectionate. They enjoy a quiet environment and are perfect lap cats.',
      diet: 'High-quality cat food with adequate protein. May need special food for hairball control.',
      careTips: ['Daily grooming required', 'Keep eyes clean', 'Indoor living recommended', 'Regular vet checkups'],
      healthIssues: ['Polycystic kidney disease', 'Respiratory issues', 'Eye problems', 'Dental disease'],
      videos: [
        { title: 'Persian Cat Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' },
        { title: 'Grooming Your Persian Cat', url: 'https://www.youtube.com/watch?v=Zs8siLxHQfg' },
      ],
      imageUrl: 'https://images.unsplash.com/photo-1589883661923-6476cb0ae9f2?w=800&h=500&fit=crop',
    },
    {
      id: 'siamese',
      name: 'Siamese',
      description: 'Vocal and social cats with striking blue eyes and color-point coats.',
      temperament: 'Highly intelligent, vocal, and social. They form strong bonds with their owners.',
      diet: 'High-protein diet with quality ingredients. Monitor weight carefully.',
      careTips: ['Provide mental stimulation', 'Interactive play daily', 'Social interaction essential', 'Minimal grooming needed'],
      healthIssues: ['Dental issues', 'Respiratory problems', 'Progressive retinal atrophy', 'Amyloidosis'],
      videos: [{ title: 'Siamese Cat Personality and Care', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800&h=500&fit=crop',
    },
    {
      id: 'maine-coon',
      name: 'Maine Coon',
      description: 'Large, gentle giants with tufted ears and bushy tails.',
      temperament: 'Friendly, playful, and adaptable. Great with families and other pets.',
      diet: 'High-calorie diet to support their large size. Quality protein sources essential.',
      careTips: ['Regular brushing', 'Provide climbing structures', 'Monitor for hip dysplasia', 'Plenty of space to roam'],
      healthIssues: ['Hip dysplasia', 'Hypertrophic cardiomyopathy', 'Spinal muscular atrophy'],
      videos: [{ title: 'Maine Coon Cat Complete Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=500&fit=crop',
    },
    {
      id: 'british-shorthair',
      name: 'British Shorthair',
      description: 'Sturdy, round-faced cats with dense coats and calm demeanor.',
      temperament: 'Easy-going, loyal, and independent. Good with children and other pets.',
      diet: 'Balanced diet with controlled portions to prevent obesity.',
      careTips: ['Weekly brushing', 'Monitor weight', 'Regular play sessions', 'Annual vet visits'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Obesity', 'Dental disease'],
      videos: [{ title: 'British Shorthair Cat Care', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=800&h=500&fit=crop',
    },
    {
      id: 'ragdoll',
      name: 'Ragdoll',
      description: 'Large, docile cats known for going limp when picked up.',
      temperament: 'Gentle, affectionate, and relaxed. Excellent family companions.',
      diet: 'High-quality protein-rich diet. Monitor portions to prevent obesity.',
      careTips: ['Regular grooming', 'Indoor only', 'Gentle handling', 'Interactive toys'],
      healthIssues: ['Hypertrophic cardiomyopathy', 'Polycystic kidney disease', 'Bladder stones'],
      videos: [{ title: 'Ragdoll Cat Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=800&h=500&fit=crop',
    },
  ],
  dog: [
    {
      id: 'golden-retriever',
      name: 'Golden Retriever',
      description: 'Friendly, intelligent, and devoted dogs that make excellent family pets.',
      temperament: 'Friendly, intelligent, reliable, and trustworthy. Great with children and other pets.',
      diet: 'High-quality dog food appropriate for their age and activity level. Monitor portions to prevent obesity.',
      careTips: ['Daily exercise required', 'Regular grooming', 'Mental stimulation', 'Socialization important'],
      healthIssues: ['Hip dysplasia', 'Elbow dysplasia', 'Heart disease', 'Cancer'],
      videos: [{ title: 'Golden Retriever Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=800&h=500&fit=crop',
    },
    {
      id: 'german-shepherd',
      name: 'German Shepherd',
      description: 'Intelligent, loyal working dogs known for their versatility and trainability.',
      temperament: 'Confident, courageous, and smart. Excellent working and family dogs.',
      diet: 'High-protein diet to support their active lifestyle. Large breed formula recommended.',
      careTips: ['Extensive exercise needed', 'Mental challenges', 'Early socialization', 'Regular grooming'],
      healthIssues: ['Hip and elbow dysplasia', 'Degenerative myelopathy', 'Bloat'],
      videos: [{ title: 'German Shepherd Training and Care', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=500&fit=crop',
    },
    {
      id: 'labrador-retriever',
      name: 'Labrador Retriever',
      description: 'Outgoing, friendly dogs that are one of the most popular breeds worldwide.',
      temperament: 'Friendly, active, and outgoing. Excellent family dogs and working companions.',
      diet: 'Quality dog food with controlled portions. Labs are prone to obesity.',
      careTips: ['Daily vigorous exercise', 'Swimming opportunities', 'Training from young age', 'Regular vet checkups'],
      healthIssues: ['Hip and elbow dysplasia', 'Obesity', 'Eye conditions', 'Exercise-induced collapse'],
      videos: [{ title: 'Labrador Retriever Complete Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=500&fit=crop',
    },
    {
      id: 'french-bulldog',
      name: 'French Bulldog',
      description: 'Compact, muscular dogs with distinctive bat ears and playful personalities.',
      temperament: 'Playful, adaptable, and smart. Great apartment dogs and companions.',
      diet: 'Quality small breed formula. Monitor weight carefully.',
      careTips: ['Moderate exercise', 'Keep cool in hot weather', 'Clean facial folds', 'Regular vet visits'],
      healthIssues: ['Brachycephalic syndrome', 'Hip dysplasia', 'Allergies', 'Spinal disorders'],
      videos: [{ title: 'French Bulldog Care Essentials', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=500&fit=crop',
    },
    {
      id: 'beagle',
      name: 'Beagle',
      description: 'Merry, friendly hounds with excellent noses and loving personalities.',
      temperament: 'Friendly, curious, and merry. Great with families and other dogs.',
      diet: 'Quality dog food with controlled portions. Beagles love to eat!',
      careTips: ['Daily exercise', 'Secure fencing', 'Mental stimulation', 'Regular ear cleaning'],
      healthIssues: ['Hip dysplasia', 'Epilepsy', 'Hypothyroidism', 'Ear infections'],
      videos: [{ title: 'Beagle Training and Care', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800&h=500&fit=crop',
    },
  ],
  bird: [
    {
      id: 'african-grey-parrot',
      name: 'African Grey Parrot',
      description: 'Highly intelligent parrots known for their exceptional talking ability and cognitive skills.',
      temperament: 'Intelligent, sensitive, and social. Require significant mental stimulation and interaction.',
      diet: 'High-quality pellets, fresh fruits, vegetables, and occasional nuts. Avoid avocado and chocolate.',
      careTips: ['Daily interaction required', 'Large cage needed', 'Mental enrichment essential', 'Regular vet checkups'],
      healthIssues: ['Feather plucking', 'Calcium deficiency', 'Psittacine beak and feather disease', 'Respiratory infections'],
      videos: [{ title: 'African Grey Parrot Care Guide', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'cockatiel',
      name: 'Cockatiel',
      description: 'Small, friendly parrots with distinctive crests and cheerful personalities.',
      temperament: 'Friendly, social, and affectionate. Great for first-time bird owners.',
      diet: 'Quality pellets, seeds, fresh vegetables, and occasional fruits.',
      careTips: ['Daily out-of-cage time', 'Social interaction', 'Toys for enrichment', 'Regular nail trimming'],
      healthIssues: ['Fatty liver disease', 'Egg binding in females', 'Respiratory infections', 'Psittacosis'],
      videos: [{ title: 'Cockatiel Care Basics', url: 'https://www.youtube.com/watch?v=JFtB_9aW0bg' }],
      imageUrl: 'https://images.unsplash.com/photo-1544923408-75c5cef46f14?w=800&h=500&fit=crop',
    },
    {
      id: 'budgerigar',
      name: 'Budgerigar (Budgie)',
      description: 'Small, colorful parakeets that are popular and easy to care for.',
      temperament: 'Playful, social, and can learn to talk. Great for beginners.',
      diet: 'Quality seed mix or pellets, fresh vegetables, and occasional fruits.',
      careTips: ['Keep in pairs if possible', 'Daily interaction', 'Provide toys', 'Clean cage regularly'],
      healthIssues: ['Tumors', 'Mites', 'Respiratory infections', 'Egg binding'],
      videos: [{ title: 'Budgie Care Complete Guide', url: 'https://www.youtube.com/watch?v=aZRV7jPvqIo' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'macaw',
      name: 'Macaw',
      description: 'Large, colorful parrots with powerful beaks and vibrant personalities.',
      temperament: 'Intelligent, social, and can be loud. Require experienced owners.',
      diet: 'High-quality pellets, nuts, fruits, and vegetables. Large portions needed.',
      careTips: ['Very large cage required', 'Extensive daily interaction', 'Strong toys needed', 'Regular training'],
      healthIssues: ['Feather plucking', 'Proventricular dilatation disease', 'Psittacosis', 'Beak malformations'],
      videos: [{ title: 'Macaw Care and Training', url: 'https://www.youtube.com/watch?v=Yz_K8Gx6eoQ' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
    {
      id: 'lovebird',
      name: 'Lovebird',
      description: 'Small, affectionate parrots known for their strong pair bonds.',
      temperament: 'Affectionate, energetic, and social. Can be territorial.',
      diet: 'Quality pellets, seeds, fresh vegetables, and fruits.',
      careTips: ['Keep in pairs or provide extensive interaction', 'Daily playtime', 'Provide toys', 'Regular bathing'],
      healthIssues: ['Egg binding', 'Psittacosis', 'Feather plucking', 'Respiratory infections'],
      videos: [{ title: 'Lovebird Care Essentials', url: 'https://www.youtube.com/watch?v=8pU0kF_NSRI' }],
      imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=500&fit=crop',
    },
  ],
};
