/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VideoLink {
    id: VideoId;
    url: string;
    title: string;
    description: string;
    category: VideoCategory;
    uploadedBy: Principal;
}
export interface PetCategory {
    name: string;
    description: string;
    image?: ExternalBlob;
    videos: Array<YoutubeVideo>;
}
export type Timestamp = bigint;
export type PetType = {
    __kind__: "cat";
    cat: null;
} | {
    __kind__: "dog";
    dog: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bird";
    bird: null;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface HealthContent {
    title: string;
    description: string;
    petType: PetType;
    category: string;
    videos: Array<YoutubeVideo>;
}
export interface Favorite {
    name: string;
    videoId: VideoId;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Breed {
    name: string;
    description: string;
    category: string;
    image?: ExternalBlob;
    videos: Array<YoutubeVideo>;
}
export interface Pet {
    id: PetId;
    age: bigint;
    weight?: bigint;
    vaccinations: Array<Vaccination>;
    name: string;
    petType: PetType;
    lastVaccinatedDate?: Timestamp;
    gender: Gender;
    breed?: string;
    photo?: ExternalBlob;
}
export type VideoCategory = {
    __kind__: "healthTopic";
    healthTopic: string;
} | {
    __kind__: "petType";
    petType: PetType;
} | {
    __kind__: "breed";
    breed: string;
};
export type PetId = bigint;
export type Gender = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
};
export type VideoId = bigint;
export interface Vaccination {
    name: string;
    completed: boolean;
    dueDate: Timestamp;
    reminderFrequency: VaccinationFrequency;
}
export interface YoutubeVideo {
    url: string;
    title: string;
}
export interface UserProfile {
    favorites: Array<Favorite>;
    name: string;
    pets: Array<Pet>;
    profilePhoto?: ExternalBlob;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VaccinationFrequency {
    everyYear = "everyYear",
    everyThreeYears = "everyThreeYears"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminVideoLink(video: VideoLink): Promise<VideoId>;
    addBreed(breed: Breed): Promise<void>;
    addFavorite(videoId: VideoId, name: string): Promise<void>;
    addHealthContent(content: HealthContent): Promise<void>;
    addPet(pet: Pet): Promise<PetId>;
    addPetCategory(category: PetCategory): Promise<void>;
    addVaccination(petId: PetId, name: string, dueDate: Timestamp, reminderFrequency: VaccinationFrequency): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    disableUser(user: Principal): Promise<void>;
    enableUser(user: Principal, profile: UserProfile): Promise<void>;
    getAllAdminVideoLinks(): Promise<Array<VideoLink>>;
    getAllBreeds(): Promise<Array<Breed>>;
    getAllFavoriteVideos(): Promise<Array<Favorite>>;
    getAllHealthContent(): Promise<Array<HealthContent>>;
    getAllPetCategories(): Promise<Array<PetCategory>>;
    getBreedsByCategory(category: string): Promise<Array<Breed>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardInfo(): Promise<UserProfile>;
    getHealthContentByCategory(category: string): Promise<Array<HealthContent>>;
    getHealthContentByPetType(petType: PetType): Promise<Array<HealthContent>>;
    getPet(petId: PetId): Promise<Pet>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVaccinationReminders(): Promise<Array<[string, Array<Vaccination>]>>;
    getVideosByCategory(category: VideoCategory): Promise<Array<VideoLink>>;
    isCallerAdmin(): Promise<boolean>;
    markVaccinationCompleted(petId: PetId, vaccinationName: string): Promise<void>;
    removeAdminVideoLink(videoId: VideoId): Promise<void>;
    removeBreed(name: string): Promise<void>;
    removeFavorite(videoId: VideoId): Promise<void>;
    removeHealthContent(title: string): Promise<void>;
    removePet(petId: PetId): Promise<void>;
    removePetCategory(name: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitOnboardingPet(pet: Pet): Promise<PetId>;
    updateAdminVideoLink(videoId: VideoId, updatedVideo: VideoLink): Promise<void>;
    updateBreed(name: string, updatedBreed: Breed): Promise<void>;
    updateHealthContent(title: string, updatedContent: HealthContent): Promise<void>;
    updatePet(petId: PetId, updatedPet: Pet): Promise<void>;
    updatePetCategory(name: string, updatedCategory: PetCategory): Promise<void>;
}
import type { Breed as _Breed, ExternalBlob as _ExternalBlob, Favorite as _Favorite, Gender as _Gender, HealthContent as _HealthContent, Pet as _Pet, PetCategory as _PetCategory, PetId as _PetId, PetType as _PetType, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, Vaccination as _Vaccination, VaccinationFrequency as _VaccinationFrequency, VideoCategory as _VideoCategory, VideoId as _VideoId, VideoLink as _VideoLink, YoutubeVideo as _YoutubeVideo, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminVideoLink(arg0: VideoLink): Promise<VideoId> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminVideoLink(to_candid_VideoLink_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminVideoLink(to_candid_VideoLink_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBreed(arg0: Breed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBreed(await to_candid_Breed_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBreed(await to_candid_Breed_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFavorite(arg0: VideoId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0, arg1);
            return result;
        }
    }
    async addHealthContent(arg0: HealthContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHealthContent(to_candid_HealthContent_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHealthContent(to_candid_HealthContent_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPet(arg0: Pet): Promise<PetId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPet(await to_candid_Pet_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPet(await to_candid_Pet_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPetCategory(arg0: PetCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPetCategory(await to_candid_PetCategory_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPetCategory(await to_candid_PetCategory_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addVaccination(arg0: PetId, arg1: string, arg2: Timestamp, arg3: VaccinationFrequency): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVaccination(arg0, arg1, arg2, to_candid_VaccinationFrequency_n24(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVaccination(arg0, arg1, arg2, to_candid_VaccinationFrequency_n24(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async disableUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableUser(arg0);
            return result;
        }
    }
    async enableUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableUser(arg0, await to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableUser(arg0, await to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllAdminVideoLinks(): Promise<Array<VideoLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminVideoLinks();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminVideoLinks();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBreeds(): Promise<Array<Breed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBreeds();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBreeds();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFavoriteVideos(): Promise<Array<Favorite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFavoriteVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFavoriteVideos();
            return result;
        }
    }
    async getAllHealthContent(): Promise<Array<HealthContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHealthContent();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHealthContent();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPetCategories(): Promise<Array<PetCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPetCategories();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPetCategories();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBreedsByCategory(arg0: string): Promise<Array<Breed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBreedsByCategory(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBreedsByCategory(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardInfo(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardInfo();
                return from_candid_UserProfile_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardInfo();
            return from_candid_UserProfile_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthContentByCategory(arg0: string): Promise<Array<HealthContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthContentByCategory(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthContentByCategory(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthContentByPetType(arg0: PetType): Promise<Array<HealthContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthContentByPetType(to_candid_PetType_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthContentByPetType(to_candid_PetType_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPet(arg0: PetId): Promise<Pet> {
        if (this.processError) {
            try {
                const result = await this.actor.getPet(arg0);
                return from_candid_Pet_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPet(arg0);
            return from_candid_Pet_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVaccinationReminders(): Promise<Array<[string, Array<Vaccination>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVaccinationReminders();
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVaccinationReminders();
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCategory(arg0: VideoCategory): Promise<Array<VideoLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(to_candid_VideoCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(to_candid_VideoCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markVaccinationCompleted(arg0: PetId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markVaccinationCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markVaccinationCompleted(arg0, arg1);
            return result;
        }
    }
    async removeAdminVideoLink(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminVideoLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminVideoLink(arg0);
            return result;
        }
    }
    async removeBreed(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBreed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBreed(arg0);
            return result;
        }
    }
    async removeFavorite(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async removeHealthContent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHealthContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHealthContent(arg0);
            return result;
        }
    }
    async removePet(arg0: PetId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePet(arg0);
            return result;
        }
    }
    async removePetCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePetCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePetCategory(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitOnboardingPet(arg0: Pet): Promise<PetId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOnboardingPet(await to_candid_Pet_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOnboardingPet(await to_candid_Pet_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAdminVideoLink(arg0: VideoId, arg1: VideoLink): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminVideoLink(arg0, to_candid_VideoLink_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminVideoLink(arg0, to_candid_VideoLink_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBreed(arg0: string, arg1: Breed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBreed(arg0, await to_candid_Breed_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBreed(arg0, await to_candid_Breed_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHealthContent(arg0: string, arg1: HealthContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHealthContent(arg0, to_candid_HealthContent_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHealthContent(arg0, to_candid_HealthContent_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePet(arg0: PetId, arg1: Pet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePet(arg0, await to_candid_Pet_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePet(arg0, await to_candid_Pet_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePetCategory(arg0: string, arg1: PetCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePetCategory(arg0, await to_candid_PetCategory_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePetCategory(arg0, await to_candid_PetCategory_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Breed_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Breed): Promise<Breed> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_HealthContent_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthContent): HealthContent {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_PetCategory_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PetCategory): Promise<PetCategory> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_PetType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PetType): PetType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_Pet_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pet): Promise<Pet> {
    return await from_candid_record_n58(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function from_candid_VaccinationFrequency_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VaccinationFrequency): VaccinationFrequency {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Vaccination_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vaccination): Vaccination {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_VideoCategory_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoCategory): VideoCategory {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_VideoLink_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoLink): VideoLink {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n46(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    url: string;
    title: string;
    description: string;
    category: _VideoCategory;
    uploadedBy: Principal;
}): {
    id: VideoId;
    url: string;
    title: string;
    description: string;
    category: VideoCategory;
    uploadedBy: Principal;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        description: value.description,
        category: from_candid_VideoCategory_n38(_uploadFile, _downloadFile, value.category),
        uploadedBy: value.uploadedBy
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    category: string;
    image: [] | [_ExternalBlob];
    videos: Array<_YoutubeVideo>;
}): Promise<{
    name: string;
    description: string;
    category: string;
    image?: ExternalBlob;
    videos: Array<YoutubeVideo>;
}> {
    return {
        name: value.name,
        description: value.description,
        category: value.category,
        image: record_opt_to_undefined(await from_candid_opt_n45(_uploadFile, _downloadFile, value.image)),
        videos: value.videos
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    petType: _PetType;
    category: string;
    videos: Array<_YoutubeVideo>;
}): {
    title: string;
    description: string;
    petType: PetType;
    category: string;
    videos: Array<YoutubeVideo>;
} {
    return {
        title: value.title,
        description: value.description,
        petType: from_candid_PetType_n40(_uploadFile, _downloadFile, value.petType),
        category: value.category,
        videos: value.videos
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    image: [] | [_ExternalBlob];
    videos: Array<_YoutubeVideo>;
}): Promise<{
    name: string;
    description: string;
    image?: ExternalBlob;
    videos: Array<YoutubeVideo>;
}> {
    return {
        name: value.name,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n45(_uploadFile, _downloadFile, value.image)),
        videos: value.videos
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favorites: Array<_Favorite>;
    name: string;
    pets: Array<_Pet>;
    profilePhoto: [] | [_ExternalBlob];
    email: string;
}): Promise<{
    favorites: Array<Favorite>;
    name: string;
    pets: Array<Pet>;
    profilePhoto?: ExternalBlob;
    email: string;
}> {
    return {
        favorites: value.favorites,
        name: value.name,
        pets: await from_candid_vec_n56(_uploadFile, _downloadFile, value.pets),
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n45(_uploadFile, _downloadFile, value.profilePhoto)),
        email: value.email
    };
}
async function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PetId;
    age: bigint;
    weight: [] | [bigint];
    vaccinations: Array<_Vaccination>;
    name: string;
    petType: _PetType;
    lastVaccinatedDate: [] | [_Timestamp];
    gender: _Gender;
    breed: [] | [string];
    photo: [] | [_ExternalBlob];
}): Promise<{
    id: PetId;
    age: bigint;
    weight?: bigint;
    vaccinations: Array<Vaccination>;
    name: string;
    petType: PetType;
    lastVaccinatedDate?: Timestamp;
    gender: Gender;
    breed?: string;
    photo?: ExternalBlob;
}> {
    return {
        id: value.id,
        age: value.age,
        weight: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.weight)),
        vaccinations: from_candid_vec_n59(_uploadFile, _downloadFile, value.vaccinations),
        name: value.name,
        petType: from_candid_PetType_n40(_uploadFile, _downloadFile, value.petType),
        lastVaccinatedDate: record_opt_to_undefined(from_candid_opt_n64(_uploadFile, _downloadFile, value.lastVaccinatedDate)),
        gender: from_candid_Gender_n65(_uploadFile, _downloadFile, value.gender),
        breed: record_opt_to_undefined(from_candid_opt_n67(_uploadFile, _downloadFile, value.breed)),
        photo: record_opt_to_undefined(await from_candid_opt_n45(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    completed: boolean;
    dueDate: _Timestamp;
    reminderFrequency: _VaccinationFrequency;
}): {
    name: string;
    completed: boolean;
    dueDate: Timestamp;
    reminderFrequency: VaccinationFrequency;
} {
    return {
        name: value.name,
        completed: value.completed,
        dueDate: value.dueDate,
        reminderFrequency: from_candid_VaccinationFrequency_n62(_uploadFile, _downloadFile, value.reminderFrequency)
    };
}
function from_candid_tuple_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, Array<_Vaccination>]): [string, Array<Vaccination>] {
    return [
        value[0],
        from_candid_vec_n59(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthTopic: string;
} | {
    petType: _PetType;
} | {
    breed: string;
}): {
    __kind__: "healthTopic";
    healthTopic: string;
} | {
    __kind__: "petType";
    petType: PetType;
} | {
    __kind__: "breed";
    breed: string;
} {
    return "healthTopic" in value ? {
        __kind__: "healthTopic",
        healthTopic: value.healthTopic
    } : "petType" in value ? {
        __kind__: "petType",
        petType: from_candid_PetType_n40(_uploadFile, _downloadFile, value.petType)
    } : "breed" in value ? {
        __kind__: "breed",
        breed: value.breed
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cat: null;
} | {
    dog: null;
} | {
    other: string;
} | {
    bird: null;
}): {
    __kind__: "cat";
    cat: null;
} | {
    __kind__: "dog";
    dog: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bird";
    bird: null;
} {
    return "cat" in value ? {
        __kind__: "cat",
        cat: value.cat
    } : "dog" in value ? {
        __kind__: "dog",
        dog: value.dog
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "bird" in value ? {
        __kind__: "bird",
        bird: value.bird
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    everyYear: null;
} | {
    everyThreeYears: null;
}): VaccinationFrequency {
    return "everyYear" in value ? VaccinationFrequency.everyYear : "everyThreeYears" in value ? VaccinationFrequency.everyThreeYears : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    female: null;
} | {
    male: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "female" in value ? {
        __kind__: "female",
        female: value.female
    } : "male" in value ? {
        __kind__: "male",
        male: value.male
    } : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoLink>): Array<VideoLink> {
    return value.map((x)=>from_candid_VideoLink_n36(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Breed>): Promise<Array<Breed>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Breed_n43(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthContent>): Array<HealthContent> {
    return value.map((x)=>from_candid_HealthContent_n48(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PetCategory>): Promise<Array<PetCategory>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PetCategory_n51(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pet>): Promise<Array<Pet>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Pet_n57(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vaccination>): Array<Vaccination> {
    return value.map((x)=>from_candid_Vaccination_n60(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, Array<_Vaccination>]>): Array<[string, Array<Vaccination>]> {
    return value.map((x)=>from_candid_tuple_n71(_uploadFile, _downloadFile, x));
}
async function to_candid_Breed_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Breed): Promise<_Breed> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_HealthContent_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthContent): _HealthContent {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_PetCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PetCategory): Promise<_PetCategory> {
    return await to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_PetType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PetType): _PetType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Pet_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Pet): Promise<_Pet> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_VaccinationFrequency_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VaccinationFrequency): _VaccinationFrequency {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Vaccination_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vaccination): _Vaccination {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_VideoCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoCategory): _VideoCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_VideoLink_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoLink): _VideoLink {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    category: string;
    image?: ExternalBlob;
    videos: Array<YoutubeVideo>;
}): Promise<{
    name: string;
    description: string;
    category: string;
    image: [] | [_ExternalBlob];
    videos: Array<_YoutubeVideo>;
}> {
    return {
        name: value.name,
        description: value.description,
        category: value.category,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.image)) : candid_none(),
        videos: value.videos
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    petType: PetType;
    category: string;
    videos: Array<YoutubeVideo>;
}): {
    title: string;
    description: string;
    petType: _PetType;
    category: string;
    videos: Array<_YoutubeVideo>;
} {
    return {
        title: value.title,
        description: value.description,
        petType: to_candid_PetType_n12(_uploadFile, _downloadFile, value.petType),
        category: value.category,
        videos: value.videos
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PetId;
    age: bigint;
    weight?: bigint;
    vaccinations: Array<Vaccination>;
    name: string;
    petType: PetType;
    lastVaccinatedDate?: Timestamp;
    gender: Gender;
    breed?: string;
    photo?: ExternalBlob;
}): Promise<{
    id: _PetId;
    age: bigint;
    weight: [] | [bigint];
    vaccinations: Array<_Vaccination>;
    name: string;
    petType: _PetType;
    lastVaccinatedDate: [] | [_Timestamp];
    gender: _Gender;
    breed: [] | [string];
    photo: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        age: value.age,
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        vaccinations: to_candid_vec_n21(_uploadFile, _downloadFile, value.vaccinations),
        name: value.name,
        petType: to_candid_PetType_n12(_uploadFile, _downloadFile, value.petType),
        lastVaccinatedDate: value.lastVaccinatedDate ? candid_some(value.lastVaccinatedDate) : candid_none(),
        gender: to_candid_Gender_n26(_uploadFile, _downloadFile, value.gender),
        breed: value.breed ? candid_some(value.breed) : candid_none(),
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.photo)) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    completed: boolean;
    dueDate: Timestamp;
    reminderFrequency: VaccinationFrequency;
}): {
    name: string;
    completed: boolean;
    dueDate: _Timestamp;
    reminderFrequency: _VaccinationFrequency;
} {
    return {
        name: value.name,
        completed: value.completed,
        dueDate: value.dueDate,
        reminderFrequency: to_candid_VaccinationFrequency_n24(_uploadFile, _downloadFile, value.reminderFrequency)
    };
}
async function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    image?: ExternalBlob;
    videos: Array<YoutubeVideo>;
}): Promise<{
    name: string;
    description: string;
    image: [] | [_ExternalBlob];
    videos: Array<_YoutubeVideo>;
}> {
    return {
        name: value.name,
        description: value.description,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.image)) : candid_none(),
        videos: value.videos
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favorites: Array<Favorite>;
    name: string;
    pets: Array<Pet>;
    profilePhoto?: ExternalBlob;
    email: string;
}): Promise<{
    favorites: Array<_Favorite>;
    name: string;
    pets: Array<_Pet>;
    profilePhoto: [] | [_ExternalBlob];
    email: string;
}> {
    return {
        favorites: value.favorites,
        name: value.name,
        pets: await to_candid_vec_n34(_uploadFile, _downloadFile, value.pets),
        profilePhoto: value.profilePhoto ? candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.profilePhoto)) : candid_none(),
        email: value.email
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: VideoId;
    url: string;
    title: string;
    description: string;
    category: VideoCategory;
    uploadedBy: Principal;
}): {
    id: _VideoId;
    url: string;
    title: string;
    description: string;
    category: _VideoCategory;
    uploadedBy: Principal;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        description: value.description,
        category: to_candid_VideoCategory_n10(_uploadFile, _downloadFile, value.category),
        uploadedBy: value.uploadedBy
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "healthTopic";
    healthTopic: string;
} | {
    __kind__: "petType";
    petType: PetType;
} | {
    __kind__: "breed";
    breed: string;
}): {
    healthTopic: string;
} | {
    petType: _PetType;
} | {
    breed: string;
} {
    return value.__kind__ === "healthTopic" ? {
        healthTopic: value.healthTopic
    } : value.__kind__ === "petType" ? {
        petType: to_candid_PetType_n12(_uploadFile, _downloadFile, value.petType)
    } : value.__kind__ === "breed" ? {
        breed: value.breed
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "cat";
    cat: null;
} | {
    __kind__: "dog";
    dog: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "bird";
    bird: null;
}): {
    cat: null;
} | {
    dog: null;
} | {
    other: string;
} | {
    bird: null;
} {
    return value.__kind__ === "cat" ? {
        cat: value.cat
    } : value.__kind__ === "dog" ? {
        dog: value.dog
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "bird" ? {
        bird: value.bird
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VaccinationFrequency): {
    everyYear: null;
} | {
    everyThreeYears: null;
} {
    return value == VaccinationFrequency.everyYear ? {
        everyYear: null
    } : value == VaccinationFrequency.everyThreeYears ? {
        everyThreeYears: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
}): {
    other: string;
} | {
    female: null;
} | {
    male: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "female" ? {
        female: value.female
    } : value.__kind__ === "male" ? {
        male: value.male
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Vaccination>): Array<_Vaccination> {
    return value.map((x)=>to_candid_Vaccination_n22(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Pet>): Promise<Array<_Pet>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Pet_n19(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
